name: redis-deployment
releases:
  - name: &release_name redis
    version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

jobs:
- name: redis
  instances: 1
  templates:
  - name: redis
    release: *release_name
  properties:
    redis:
      config_command: 1
      port: 6379
  vm_type: medium
  persistent_disk_type: ten
  stemcell: trusty
  networks:
  - name: &network_name redis-network

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
