azs:
- name: z1
- name: z2
- name: z3
compilation:
  az: z1
  network: kafka
  reuse_compilation_vms: true
  vm_type: minimal
  workers: 6
disk_types:
- disk_size: 1024
  name: 1GB
- disk_size: 5120
  name: 5GB
- disk_size: 10240
  name: 10GB
- disk_size: 100240
  name: 100GB
- disk_size: 10_000
  name: ten
networks:
- name: kafka
  subnets:
  - azs: [z1, z2, z3]
    cloud_properties:
      name: random
    gateway: 10.244.0.1
    range: 10.244.0.0/16
    reserved: [10.244.0.1, 10.244.1.1, 10.244.2.1, 10.244.3.1]
    static:
    - 10.244.0.2 - 10.244.0.100
vm_types:
- name: minimal
- name: small
- name: small-highmem
- name: medium
